### ISSUE TITLE
4:3 ratio

### ISSUE THREAD

**Issue by availableRadu** [SeekyCt/spm-practice-codes#27]
the practice menu and the hud isn't adapted to the wii 4:3 format, and some informations are just off screen.

**Comment by SeekyCt** [comment]
Oh, sorry about that, I completely forgot about 4:3 :/
Thanks for reporting, I'll try improve this soon

**Comment by SeekyCt** [comment]
Everything should be visible in 4:3 as of https://github.com/SeekyCt/spm-practice-codes/commit/e4309c62f86c6ba9a2fcb9fbd8dc8e3fa1c25a99, will be included in the next release
