### ISSUE TITLE
Sequence value list

### ISSUE THREAD

**Issue by Firegloom** [SeekyCt/spm-practice-codes#67]
Can you make a list of which events are associated with each sequence value, like your list of map IDs, if there isn't one already?

**Comment by shiken-yme** [comment]
https://docs.google.com/document/d/1gxALlevkiz-i18lJG700VJF4_NzesA30X1hj0atk1vg/

**Comment by Firegloom** [comment]
Thank you! Can you link it in the manual like the map ID list is?
